### ISSUE TITLE
Possible memory leak

### ISSUE THREAD

**Issue by phoe** [g000001/srfi-229#1]
https://github.com/g000001/srfi-229/blob/859f83987e7a0fd8ff7cfe6de78b038bf1517bca/srfi-229.lisp#L18

This is going to keep all procedures in `*tagged-procedures*` forever, preventing their garbage collection. I'd suggest using either a weak hash table with function objects as weak keys (which would cause entries to be automatically garbage collected) or funcallable instances (which could carry tag information on themselves).

**Comment by g000001** [comment]
Thank you for your comment!
I have been fixed codes to use trivial-garbage for GC stuffs. 
f68653a13b0be78ef0dae9c37777d29425aee354

Also, Spec mentions to using kind of 'weak hashtables' but does not requires it.
https://srfi.schemers.org/srfi-229/srfi-229.html

Thank you.
